<a href="https://colab.research.google.com/github/17kriti/NUMPY-BASICS/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

In [1]:
 import numpy as np

x =[1,2,3,4]
y = np.array([1,2,3,4,5])
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [2]:
y=[1,2,3,4]
print(y)
print(type(y))


[1, 2, 3, 4]
<class 'list'>


**Array**

In [3]:
import numpy as np
x =[1,2,3,4]

y = np.array(x)
print(y)

[1 2 3 4]


In [6]:
l =[]

for i in range(1,5):
  int_1 = int(input("enter:"))
  l.append(int_1)
print(np.array(l))

enter:11
enter:12
enter:3
enter:4
[11 12  3  4]


In [7]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [8]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [9]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


**FUNCTION**

In [10]:
import numpy as np
ar_zero = np.zeros(4)

ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
import numpy as np

ar_one = np.ones(4)

print(ar_one)

[1. 1. 1. 1.]


In [12]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [13]:
import numpy as np

ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [14]:
ar_dg = np.eye(3)
print(ar_dg)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
ar_dg = np.eye(3,5)
print(ar_dg)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [17]:
ar_lin = np.linspace(0,20, num = 5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


**RANDOM** **NUMBER**

In [18]:
import numpy as np

var = np.random.rand(4)

print(var)

[0.87040234 0.98506341 0.88064672 0.93982866]


In [19]:
var1 = np.random.rand(2,5)
print(var1)

[[0.59844668 0.20187078 0.58149245 0.11110054 0.05125015]
 [0.98242384 0.77931114 0.22261722 0.91664663 0.89942715]]


In [20]:
var2 = np.random.randn(5)
print(var2)

[-0.47627612  0.77668234 -0.42409881 -0.02562271  1.58385811]


In [21]:
var3 = np.random.ranf(4)
print(var3)

[0.55330167 0.14373588 0.08389323 0.23587755]


In [22]:
var4 = np.random.randint(5,20,5)
print(var4)

[10 19  8 19  7]


**DATA** **TYPE**

In [23]:
import numpy as np

var = np.array([1,2,3,4])

print("Data type: ",var.dtype)

Data type:  int64


In [24]:
var = np.array([1.0,1.2,1.3])

print("Data type : ", var.dtype)

Data type :  float64


In [25]:
var = np.array(["S","A","B"])

print("Data type: ",var.dtype)

Data type:  <U1


In [26]:
var = np.array(["S","A","B",1,2,3,4])

print("Data type: ",var.dtype)

Data type:  <U21


In [27]:
x = np.array([1,2,3,4],dtype = np.int8)

print(x.dtype)

int8


In [28]:
x1 = np.array([1,2,3,4],dtype = "f")

print(x1.dtype)
print(x1)

float32
[1. 2. 3. 4.]


In [29]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

new_one = np.int_(new)

print(x2.dtype)
print(new.dtype)
print(new_one.dtype)
print(x2)
print(new)
print(new_one)

int64
float32
int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [30]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


**ARITHMETIC** **OPERATION**

In [31]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var + 3

print(varadd)

[4 5 6 7]


In [32]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2

print(varadd)

[2 4 6 8]


In [33]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,var2)

print(varadd)

[2 4 6 8]


In [34]:
var = np.array([1,2,3,4])

varadd = var - 3

print(varadd)

[-2 -1  0  1]


In [35]:
var = np.array([1,2,3,4])

varadd = var * 3

print(varadd)

[ 3  6  9 12]


In [36]:
var = np.array([1,2,3,4])

varadd = var / 3

print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [37]:
var = np.array([1,2,3,4])

varadd = var % 3

print(varadd)

[1 2 0 1]


In [38]:
var = np.array([1,2,3,4])

varadd = np.reciprocal(var)

print(varadd)

[1 0 0 0]


**2D** **ARRAY** **OPERATION**

In [39]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()
varadd2 = var21 + var22

print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


**ARITHMETIC** **FUNCTION**

In [40]:
import numpy as np

var = np.array([1,2,3,4,5,3,2])

print(np.min(var),np.argmin(var))
print(np.max(var),np.argmax(var))
print(np.sqrt(var))

1 0
5 4
[1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [41]:
var1 = np.array([[2,1,3],[9,5,6]])

print(np.min(var1,axis=0))

[2 1 3]


In [42]:
var2 = np.array([1,2,3])

print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


**SHAPE**

In [43]:
import numpy as np

var = np.array([[1,2],[1,2]])

print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [44]:
var1 = np.array([1,2,3,4], ndmin=4)

print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


**RESHAPE**

In [45]:
var2 = np.array([1,2,3,4,5,6])
print(var2)

print(var2.ndim)
print()
x = var2.reshape(3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [46]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var2.ndim)

print()

x1 = var3.reshape(2,3,2)

print(x1)
print(x1.ndim)


print()

one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


**BROADCASTING**

In [47]:
import numpy as np

var1 = np.array([1,2,3])
print(var1.shape)
print()
print(var1)
print()

var2 = np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var2)
print()

print(var1 + var2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [48]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


**INDEXING**

In [49]:
import numpy as np

var = np.array([9,8,7,6])

print(var[1])

8


In [50]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)

print()

print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [51]:
var2 = np.array([[[1,2],[6,7]]])

print(var2)

print(var2.ndim)
print()

print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


**SLICING**

In [52]:
import numpy as np

var = np.array([9,8,7,6,5,4,3])

print(var)
print()
print("2 to 5", var[1:5])

print("2 to end", var[1:])

print("start to 5", var[:5])

print("stop : ", var[::2])

[9 8 7 6 5 4 3]

2 to 5 [8 7 6 5]
2 to end [8 7 6 5 4 3]
start to 5 [9 8 7 6 5]
stop :  [9 7 5 3]


In [53]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])

print(var1)

print()

print("8 to 5", var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5 [12 13 14 15]


**ITERATION**

In [54]:
import numpy as np

var = np.array([9,8,7,6,5,4])
print(var)
print()
for i in var:
  print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [55]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
for j in var1:
  print(j)
print()

for k in var1:
  for l in k:
    print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [56]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])

print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
  print(i)

[[[9 8 7 6]
  [1 2 3 4]]]
3

9
8
7
6
1
2
3
4


In [57]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])

print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
  print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


**COPY** **AND** **VIEW**

In [58]:
import numpy as np

var = np.array([1,2,3,4])

co = var.copy()
var[1]=40
print("var:",var)
print("copy:",co)

var: [ 1 40  3  4]
copy: [1 2 3 4]


In [59]:
x = np.array([9,8,7,6,5])

vi = x.view()
x[1]=40
print("x:",x)
print("vi:",vi)

x: [ 9 40  7  6  5]
vi: [ 9 40  7  6  5]


**JOINING**

In [60]:
import numpy as np

var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1))

print(ar)

[1 2 3 4 9 8 7 6]


In [61]:
from numpy.lib.twodim_base import vander

vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

ar_new = np.concatenate((vr,vr1),axis=1)


print(vr)
print()
print(vr1)
print()
print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [62]:
var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var_1,var_2),axis=1)
a_new1 = np.hstack((var_1,var_2)) #row
a_new2 = np.vstack((var_1,var_2)) #column
a_new3 = np.dstack((var_1,var_2)) # height

print(a_new)
print()
print(a_new1)
print()
print(a_new2)
print()
print(a_new3)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


**SPLITING**

In [63]:
import numpy as np

var = np.array([1,2,3,4,5,6])

print(var)

ar = np.array_split(var,3)
print()
print(ar)
print(ar[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [64]:
var1 = np.array([[1,2],[3,4],[5,6]])

print(var)

ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis=1)
print()
print(ar1)
print()
print(ar2)

[1 2 3 4 5 6]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]


**SEARCH**

In [65]:
import numpy as np

var = np.array([4,2,3,4,2,5,2,5,6,7])

x = np.where((var%2) == 0)

print(x)

(array([0, 1, 3, 4, 6, 8]),)


In [66]:
var1 = np.array([1,2,3,4,9,10])

x1 = np.searchsorted(var1,[5,6,7],side ="right")

print(x1)

[4 4 4]


**SORT**

In [67]:
var_1 = np.array([4,2,3,1,12,5,22,52,6,7])

print(np.sort(var_1))

[ 1  2  3  4  5  6  7 12 22 52]


In [68]:
var_1 = np.array(["a","s","d","f"])

print(np.sort(var_1))

['a' 'd' 'f' 's']


In [69]:
var_1 = np.array([[4,2,3],[1,12,5],[22,52,6]])

print(np.sort(var_1))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


**FILTER**

In [70]:
import numpy as np

var_3 = np.array(["a","s","d","f"])

f =[True ,False,False, True]

new_a = var_3[f]

print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>


**SHUFFLE**

In [71]:
import numpy as np

var = np.array([1,2,3,4,5])

np.random.shuffle(var)

print(var)

[2 4 3 5 1]


**UNIQUE**

In [72]:
var1 = np.array([1,2,3,4,2,5,6,2,7])

x = np.unique(var1, return_index = True)

print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 6, 8]))


**RESIZE**

In [73]:
var_1 = np.array([1,2,3,4,5,6])

y = np.resize(var_1,(2,3))

print(y)

[[1 2 3]
 [4 5 6]]


**FLATTEN**

In [74]:
var_1 = np.array([1,2,3,4,5,6])

y = np.resize(var_1,(3,2))
print(y)
print()

print("Flatten: ",y.flatten( order ="C"))

print("Ravel: ",np.ravel(y, order="A"))

[[1 2]
 [3 4]
 [5 6]]

Flatten:  [1 2 3 4 5 6]
Ravel:  [1 2 3 4 5 6]


**INSERT**

In [75]:
import numpy as np

var = np.array([1,2,3,4])

print(var)

# v = np.insert(var, [2,4], 40)
v = np.append(var,6.5)
print()
print(v)

[1 2 3 4]

[1.  2.  3.  4.  6.5]


In [76]:
var1 = np.array([[1,2,3],[1,2,3]])

#v1 = np.insert(var1, 2, 6, axis =1)

v1 = np.append(var1,[[45,44,23]], axis=0)

print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [45 44 23]]


**DELETE**

In [77]:
import numpy as np

var1 = np.array([1,2,3,4])

print(var1)

d = np.delete(var1, 2)
print(d)

[1 2 3 4]
[1 2 4]


**MATRIX**

In [78]:
import numpy as np

var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])
print(var)
print(type(var))
print()
print(var+var2)
print()
print(var*var2)
print()
print(var.dot(var2))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[2 4]
 [2 4]]

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


In [79]:
var1 = np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))
print(var1*var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>
[[1 4 9]
 [1 4 9]]


**TRANSPOSE**

In [80]:
import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


**SWAPAXES**

In [81]:
import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [82]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


**INVERSE**

In [83]:
import numpy as np
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()

print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


**POWER**

In [84]:
import numpy as np

var4 = np.matrix([[1,2],[3,4]])
print(var4)

print()
print(np.linalg.matrix_power(var4,2))
print()
print(np.linalg.matrix_power(var4,0))
print()
print(np.linalg.matrix_power(var4,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


**DETERMINANTE**

In [85]:
var5 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
